version: "3.8"

services:

  backoffice-db:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: backoffice
      MYSQL_DATABASE: backoffice
      MYSQL_USER: backoffice
      MYSQL_PASSWORD: backoffice
    ports:
      - 3306:3306
    volumes:
      - "./backoffice-service/src/main/db/:/docker-entrypoint-initdb.d/"
    command: [ "--default-authentication-plugin=mysql_native_password" ]
